os:
- linux
language: node_js
node_js:
- '8'
before_install:
  - npm i -g npm@6.0.0
cache:
  directories:
    - node_modules
script:
  - npm run lint && npm test && npm run build && npm run test:e2e:ci
